### PR TITLE
Setup.py does not try to load requests anymore

### PR DESCRIPTION
**Pull request by pomarec**
When pysendy was in a requirements.txt (pip) it crashed because requests was not installed yet.

### CODE REVIEW

**Comment by thiagofa** [comment]
Hello Pierre,

I didn't understand your commit.
You just updated the "version" variable attribution. Is that correct?

**Comment by pomarec** [comment]
Yes, so it does not try to import pysendy,which tries to import requests. It didn't work for me if I did not install request before installing pysendy.

**Comment by OddBloke** [comment]
We're hitting this as well.

The following line:

``` py
version = __import__('pysendy').__version__
```

causes a traceback on _install_ if you don't already have requests installed (see the end of this comment). This means that if you are installing it fresh using pip (in, for example, a new production environment), you will never succeed.

I recommend merging this PR.

Traceback:

``` pytraceback
$ pip install pysendy
Downloading/unpacking pysendy
  Downloading pysendy-0.0.3.tar.gz
  Running setup.py egg_info for package pysendy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/daniel/.virtualenvs/ott/build/pysendy/setup.py", line 5, in <module>
        version = __import__('pysendy').__version__
      File "pysendy/__init__.py", line 2, in <module>
        from .pysendy import *
      File "pysendy/pysendy.py", line 3, in <module>
        import requests
    ImportError: No module named requests
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/daniel/.virtualenvs/ott/build/pysendy/setup.py", line 5, in <module>

    version = __import__('pysendy').__version__

  File "pysendy/__init__.py", line 2, in <module>

    from .pysendy import *

  File "pysendy/pysendy.py", line 3, in <module>

    import requests

ImportError: No module named requests

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/daniel/.virtualenvs/ott/build/pysendy
Storing complete log in /home/daniel/.pip/pip.log
```

**Comment by OddBloke** [comment]
Any advance on this? We've resorted to including the full library in our tree to avoid this problem.

**Comment by matejc** [comment]
@thiagofa,
When importing itself, in the setup.py before actually installing its dependencies it will fail.

Lets look at the time line of installing `pysendy` in the environment without `requests` package:
1. when it comes to this line: `version = __import__('pysendy').__version__`
2. it then imports the `./pysendy/__init__.py`
3. it then imports everything from `./pysendy/pysendy.py` (`from .pysendy import *`)
4. then it tries to import `requests`, and it fails in the environment that has not got `requests` package already installed
and it fails before it gets to the `__version__` of `pysendy`.

Therefore if you import the pysendy package before installation process, you loose one of setuptools features - installation of dependencies, because it imports the dependencies before the installation process even begins.

I also recommend merging this pull request.

**Pull request merged**
